### PR TITLE
Fix for command permissions in python3

### PR DESCRIPTION
**Pull request by GiovanniMCMXCIX**
image

tested in python2 too

### CODE REVIEW

**Comment by b1naryth1ef** [comment]
This won't work, its valid for a commands level to be a plain integer as well. The true fix is likely to make sure holsters enum comparison functions work correctly on Python 3.x

**Comment by cookkkie** [comment]
```python3
if six.PY3:
    from enum import Enum
else:
    from holster.enum import Enum
```

Or make that code live in holster.

**Comment by b1naryth1ef** [comment]
Python 3 enum implementation isn't 1-to-1 with Holster, they work differently so that won't work either w/o large refactors.

**Comment by GiovanniMCMXCIX** [comment]
Not needed anymore f098241

**Pull request closed without merging**
