### PR TITLE
Fixes #100: Remove old entry from voice_states if user device changes

### LINKED ISSUE #100: Guilds voice_states cache sometimes corrupts itself
Sometimes (I guess during a Discord Gateway problem, such as a restart), the guild voice_states still contains invalid entries.
In my case, voice_states still contains a state for a player which says is still in a channel, but according to Discord Client, there's nobody in that channel.

Here's a gif of what happen:
Gif of problem

If it may help, here's [how I use voice_states](https://framagit.org/kyriog/crewbot/blob/dd89aa50051d321e9cae9938f7f2792cc7dd1832/plugins/vocal_crews.py#L91) in my `VoiceStateUpdate` event.

As a workaround, is there any way to "force update" the voice_states array, using a scheduled task?

Thanks for your help! :D

### PR DESCRIPTION
**Pull request by kyriog**

### CODE REVIEW

**Comment by kyriog** [comment]
Hey @b1naryth1ef, any chance you could have a look to this PR any time soon?
This is freezing my devs on my bot for 2 months 😢

**Comment by PixeLInc** [comment]
You.. you do realize you can literally point to your own repo in the config or just run the setup py from your modified version to install your version, right..?

**Comment by kyriog** [comment]
@PixeLInc Of course I can, but I prefer not to start a fork for a API lib.
Moreover, as suggested in the comment in #100, this PR isn't imo the right way to fix the bug, this is just a way not to break compatibility.
So if I start a bot with an implementation, then @b1naryth1ef changes this implementation, I will have to start over almost the whole bot.
This is the reason I prefer to wait for the "official" way to manage this.

**Comment by PixeLInc** [comment]
Well, you've already made a fork. That's how you edited the code.
If it's not the right way, then make it the right way. If it's not the right way, b1nzy probably won't merge it anyways and will suggest changes. 
If you point to your fork, you don't have to change anything, lol. If he changes the impl somehow then just change the 2 lines in your code, it won't affect your ENTIRE bot...

**Comment by kyriog** [comment]
Yeah, technically, this is a fok, I agree, but what I meant is I don't want fully manage, merge, update, fix… a fork for a project.

And by "changing the implementation", I mean changing the way disco manage voice_states events, which will break *every* bots which use voice_states.

The point is, there is in fact no best way to manage this, because Discord documentation doesn't tell us what is the key in a `voice_state` event.
So we could use this PR, which keep compatibility with current implementation and doesn't break other bots, but it requires to iterate twice over the current voice_states. Or, we could change this to use the `user_id` has the key, which will fix the bug, but it'll break all disco bots and the implementation could break if Discord changes his way to manage vocal connections.

As my bot is heavily based on voice_states, wether to know if a channel is empty, to know where a member is or even who is in a particular channel, choosing an implementation could completly break my bot.

**Comment by b1naryth1ef** [comment]
Sorry for missing this conversation, my personal life has been busy and I haven't had much time to spend on Github projects. Its totally reasonable for @kyriog to bump this PR, I see no reason for the aggression or line of discussion in this thread, please keep it out of my projects in the future @PixeLInc.

I ended up rewriting your patch to improve the performance instead of copying stuff around for iteration (`select_one` comes in handy here luckily) and also adding tests. Thanks anyway and apologies for the delay.

**Pull request closed without merging**
