### PR TITLE
Return png instead of webp when getting avatar image URL

### PR DESCRIPTION
**Pull request by One-Nub**
WebP images have a spotty reputation on iOS with rendering.
Changing this to a PNG lets the avatar URL display correctly on iOS.

### CODE REVIEW

**Comment by elderlabs** [comment]
Specify `fmt` in your call and you won't have this issue. Disco defaults to the `webp` format when no other format is supplied in the request. Adding 'png' to your call (`user.get_avatar_url('png')`) will correct the problem on your end, instead of defaulting the library to another image format, though mobile doesn't fully support `webp` yet. Perhaps someday soon... 🤔

**Comment by One-Nub** [comment]
The problem then is that I can't properly get gifs because the fmt check is before the gif check (just a loss of image quality I suppose if I force a gif format, and when the image is small enough I suppose that wouldn't matter)

**Comment by elderlabs** [comment]
You could do a check before making the request to see if the avatar start with `a_` to specify that it's a `gif` in the request, otherwise grab `png`.

That said, you make a valid point in this case and it makes sense to default to `png` if you want an easy way to determine whether the avatar is animated or not, and have the ability to display on mobile (which has no `webp` support on any platform at this time).

**Comment by b1naryth1ef** [comment]
I didn't give enough time to reviewing the changes around animated avatars and `get_avatar_url` / `get_icon_url`. As such I don't like the way these functions behave today. I've performed a refactor in ced2427 which provides a much better interface to getting these URLs, and separating formats based on animated/still images. Right now this commit lives in our v1.0.0 branch and I have no plans to backport it since the function signature change is breaking. Thanks for bringing this up and taking a stab at improving it regardless!

**Pull request closed without merging**
