### PR TITLE
Update gevent to 1.3.6 to support python 3.7

### PR DESCRIPTION
**Pull request by Watchful1**
See #107

### CODE REVIEW

**Comment by GiovanniMCMXCIX** [comment]
while adding support for 3.7 you should update the travis file to test for 3.7 as well

**Comment by Watchful1** [comment]
Looks like travis failed to install 3.7 on the build server

**Comment by GiovanniMCMXCIX** [comment]
please add `dist: xenial` to the travis file and don't remove 3.6 because there are a lot of people still using that version
and next time read the travis errors

**Comment by Watchful1** [comment]
Looks like the workaround suggested here worked

https://github.com/travis-ci/travis-ci/issues/9815

**Comment by b1naryth1ef** [comment]
Thanks!

**Pull request merged**
